### ISSUE TITLE
FT008 - feat: stworzenie formularza do dodawania sekcji

### ISSUE THREAD

**Issue by EMEZYK** [akademia-envelo-3/meetek-front#10]
**Story**
Po wybraniu w menu 'sekcje' , chcę być przekierowana na stronę z sekcjami, a następnie klikając w przycisk plusa, chcę przejść do formularza dodawania nowej sekcji. Formularz ma się składać z 3 pól: nazwa, opis i organizator (domyślnie mam się wyświetlać jako orgazniator). 

**Dodatkowe informacje**
Formularz powinien być walidowany.
Wszystkie widoki powinny być responsywne (breakpointy zgodne z design systemem).

**Taski blokujące**
#3 #6 #22 

**Makiety**
[FIGMA](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=0%3A1&t=ht9GjdriLijgnVFp-0)
[DESIGN SYSTEM](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=7vxrIdlO9KynFcUw-0)

**Kryteria akceptacji**
1. Wygląd formularza odwzorowany jest zgodnie z makietami Figma.
2. Formularz jest responsywny, zgodnie z ustalonymi breakpointami.
3. Jako admin chcę zobaczyć komunikaty walidacyjne dla pola nazwa:  puste pole,  min. ilość znaków: 5, max ilośc znaków: 30; dla pola opis:  puste pole, min. ilość znaków: 20, max ilośc znaków: 250.
4. Pole organizator (domyślnie osoba zalogowana wyświetla się jako organizator i  nie ma możliwości zmiany). 
5. Po kliknięciu przycisku 'Dodaj', chcę być przekierowana do widoku wszystkich sekcji.

**Comment by piodaw** [comment]
https://deploy-preview-62--meetek-envelo.netlify.app/section/add 

1. żeby prawidłowo działało trzeba się zalogować
2. wejdź na /section/add aby dodać nową sekcję

**Comment by PawelJurga** [comment]
- [ ] Wygląd formularza odwzorowany jest zgodnie z makietami Figma.

-   **po kliknięciu w pole organizator pojawia się podwójny napis**

- **brak avatara**





![Image](https://user-images.githubusercontent.com/121928858/216251644-56521ef9-a3c9-44f3-9de1-7dbe0b5ae16d.png)

- **wprowadzenie najdłuższego nazwiska w Polsce powoduję rozjechanie się formularza**


![Image](https://user-images.githubusercontent.com/121928858/216252541-d7004a6f-d375-4d9b-884c-5482a5631f3b.png)







    

- [x] Formularz jest responsywny, zgodnie z ustalonymi breakpointami.

    

- [ ] Jako admin chcę zobaczyć komunikaty walidacyjne dla pola nazwa: puste pole, min. ilość znaków: 5, max ilośc znaków: 30; dla pola opis: puste pole, min. ilość znaków: 20, max ilośc znaków: 250.
- **formularz pokazuję prawidłowo komunikaty validacyjne, jednak dalej można dodawać znaki. Myślę, że trzeba zablokować możliwość wprowadzania w formularzu większej liczby znaków, niż sugerują to komunikaty**

    

- [x] Pole organizator (domyślnie osoba zalogowana wyświetla się jako organizator i nie ma możliwości zmiany).

   


- [ ] Po kliknięciu przycisku 'Dodaj', chcę być przekierowana do widoku wszystkich sekcji.
- **po dodaniu sekcji użytkownik jest przekierowany na link https://deploy-preview-62--meetek-envelo.netlify.app , jeśli tak ma być na tym etapie, to proszę o komentarz :)**

**Comment by piodaw** [comment]
na tym etapie musi tak zostać bo jeszcze nie ma komponentu do którego ma przekierowywać

**Comment by PawelJurga** [comment]
**RETEST**
   - [x]  Wygląd formularza odwzorowany jest zgodnie z makietami Figma.

  -  **błędy poprawiono**



   

- [x]  Jako admin chcę zobaczyć komunikaty walidacyjne dla pola nazwa: puste pole, min. ilość znaków: 5, max ilośc znaków: 30; dla pola opis: puste pole, min. ilość znaków: 20, max ilośc znaków: 250.

- **zostały dodane liczniki wprowadzonych znaków dla pól "nazwa" oraz "opis". Zablokowano możliwość dodawania większej liczby znaków niż 30 dla nazwy i 250 dla opisu**

    


    

- [x] Po kliknięciu przycisku 'Dodaj', chcę być przekierowana do widoku wszystkich sekcji.

- **będzie dodane w innym tasku**
**Rekomenduję zakończenie taska :)**
