### ISSUE TITLE
FT058 - Dołączanie/opuszczanie sekcji

### ISSUE THREAD

**Issue by piodaw** [akademia-envelo-3/meetek-front#103]
***Story***
-User
- Użytkownik po kliknięciu dołącz dołącza do sekcji
- Gdy użytkownik jest członkiem sekcji ma możliwość opuszczenia sekcji

-Owner
- Po wejściu w sekcję której jest ownerem wyświetla mu się przycisk edycji sekcji

***Dodatkowe informacje***
- ~~Stworzyć efekty w ngrx obsługujące dołączanie/opuszczanie sekcji~~
- brak możliwości dołączenia/opuszczenia przez brak backendu

***Kryteria akceptacji***
- ~~Po kliknięciu przycisku dołącz użytkownik dołącza do sekcji~~
- ~~Po kliknięciu przycisku opuść użytkownik opuszcza sekcję~~
- ~~Po kliknięciu edytuj owner sekcji przechodzi do edycji sekcji~~
- jeśli użytkownik jest członkiem sekcji zmieni się button
- jeśli jest ownerem zobaczy button edytuj
- jeśli jeszcze nie dołączył zobaczy button dołącz

**Comment by piodaw** [comment]
link: https://ft058-dolaczanie-opuszczanie-sekcji--meetek-envelo.netlify.app/section/1

```json
"sections": [
    {
      "name": "Test test",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer tookwhen an unknow printer took a galley of type and scrambl",
      "sectionOwner": {
        "email": "admin@admin3.com",
        "firstName": "Admin",
        "lastName": "Paschalis Ochedoski vel Ochenduszko",
        "id": 2,
        "role": "user"
      },
      "users": [
        {
          "id": 2,
          "firstName": "Admin",
          "lastName": "Paschalis Ochedoski vel Ochenduszko"
        }
      ],
      "id": 1
    }
  ],
```

**Comment by PawelJurga** [comment]
- [x] jeśli użytkownik jest członkiem sekcji zmieni się button

- [x] jeśli jest ownerem zobaczy button edytuj

- [x] jeśli jeszcze nie dołączył zobaczy button dołącz
**Rekomenduję zakończenie taska :)**
