### ISSUE TITLE
FT011 - feat: Aktywacja/dezaktywacja kategorii

### ISSUE THREAD

**Issue by piodaw** [akademia-envelo-3/meetek-front#11]
## story ##
* Admin:
Po wejściu w kategorie:

2.  Klikając w toggla admin dezaktywuje/aktywuje sekcje

## Dodatkowe informacje ##
Stworzyć używając NgRx

## makiety ##
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=331%3A25376&t=ht9GjdriLijgnVFp-0)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0) 

## kryteria akceptacji ##

1.  Po dezaktywacji kategoria jest nieaktywna
2.  Po aktywacji kategoria jest aktywna

**Comment by piodaw** [comment]
link: https://ft011-aktywacja-dezaktywacja-kategorii--meetek-envelo.netlify.app/categories
żeby móc aktywować/dezaktywować kategorię trzeba być zalogowanym jako admin
json
```json
"categories": [
    {
      "name": "Test",
      "active": true,
      "id": 1
    }
  ],
```

**Comment by PawelJurga** [comment]
- [x] Po dezaktywacji kategoria jest nieaktywna

   

- [x]  Po aktywacji kategoria jest aktywna

**Rekomenduję zakończenie taska :)**
