### ISSUE TITLE
FT013 - feat: stworzenie elementu listy sekcji

### ISSUE THREAD

**Issue by damiankubecki** [akademia-envelo-3/meetek-front#16]
**Dodatkowe informacje**
Utworzenie elementu listy sekcji, uwzględniając podane niżej propsy. Wygląd zgodny z design system.  

## Propsy ##
1. Nazwa sekcji [required]
2. Liczba członków sekcji [required]
3. Dwie wersje (owner i user) -  if owner:  "modyfikuj" oraz "dezaktywuj/aktywuj"; if user : tylko przekierowanie do sekcji;  [optional - domyślnie wersja usera]
4. OnModify podpiętne do buttona "modyfikuj" [owner only]
5. OnDeactivate - podpięte do buttona "dezaktywuj";  [owner only]
6. OnActivate podpięte do buttona "aktywuj"  [owner only]

## Makiety ##
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=331%3A25376&t=ht9GjdriLijgnVFp-0)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0) 

## Kryteria akceptacji ##
1. Wygląd zgodny z makietami z uwzględnieniem media queries
2. Zachowanie komponentu zależne od przekazanych propsów

**Comment by jBachanek-02** [comment]
- [x]  Wygląd zgodny z makietami z uwzględnieniem media queries
     

- [x] Zachowanie komponentu zależne od przekazanych propsów
