### ISSUE TITLE
FT017 - feat: Wyświetlanie sekcji

### ISSUE THREAD

**Issue by piodaw** [akademia-envelo-3/meetek-front#18]
**Dodatkowe informacje**
Strona sekcji powinna wyglądać tak jak na makietach, powinna być również responsywna.
Na razie bez implementacji menu sekcji(tablet, desktop) i menu dolnego (mobile).
Do stora sekcji należy dodać logikę do dołączania i opuszczania sekcji. 
W body:
{
sectionId,
userId
}

**Story**
* User:
Po wybraniu w liście sekcji konkretnej sekcji, wyświetlone zostają dane sekcji:
1. Jeśli nie jestem jeszcze członkiem sekcji:  
a) informacja, ze nie jest członkiem
b) nazwa sekcji
c) organizator sekcji
d) opis sekcji
e) przycisk 'dołącz' - po kliknięciu w przycisk, user dołącza do sekcji.
2. Jeśli jestem członkiem sekcji, dane jw, zmienia się tylko: 
a) informacja, ze jestem czlonkiem
e) przycisk 'opuść' - po kliknięciu wyświetla mi się modal, czy na pewno chcę opuścić sekcję. Po kliknięciu 'anuluj' wracam do widoku sekcji bez zmian, przycisk 'potwierdź-  po kliknięciu user opuszcza sekcję.

**Taski blokujące**
#22 
#40
#34 
#47 

**Makiety**
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=250%3A8168&t=X6fc3HJFQkmcBa3D-4)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0) 

**Kryteria akceptacji**
1.  Sekcje powinny wyglądać jak na makietach, być responsywne.
2. Logika zgodna z wyżej opisanym story. 
3. W przypadku wystąpienia błędu ze strony backendu, należy wyświetlić toast z informacją o błędzie.

**Comment by piodaw** [comment]
https://ft017-wyswietlanie-sekcji--meetek-envelo.netlify.app/section/1

```json
"sections": [
    {
      "name": "Test test",
      "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer tookwhen an unknow printer took a galley of type and scrambl",
      "sectionOwner": {
        "email": "admin@admin3.com",
        "firstName": "Admin",
        "lastName": "Paschalis Ochedoski vel Ochenduszko",
        "id": 1,
        "role": "user"
      },
      "users": [],
      "id": 1
    }
  ]
```

**Comment by PawelJurga** [comment]
- [x]  Jeśli nie jestem jeszcze członkiem sekcji:
 a) informacja, ze nie jest członkiem
    b) nazwa sekcji
    c) organizator sekcji
    d) opis sekcji
    ~~e) przycisk 'dołącz' - po kliknięciu w przycisk, user dołącza do sekcji.~~ **w innym tasku**
   

- [x]  Jeśli jestem członkiem sekcji, dane jw, zmienia się tylko:
    a) informacja, ze jestem czlonkiem
    ~~e) przycisk 'opuść' - po kliknięciu wyświetla mi się modal, czy na pewno chcę opuścić sekcję. Po kliknięciu 'anuluj' wracam do widoku sekcji bez zmian, przycisk 'potwierdź- po kliknięciu user opuszcza sekcję.~~ **w innym tasku**

**Kryteria spełniono. Pozycje wykreślone zostaną przeniesione na inny task. 
Rekomenduję zakończenie taska :)**
