### ISSUE TITLE
FT022 - feat: wyświetlanie listy uczestników sekcji

### ISSUE THREAD

**Issue by EMEZYK** [akademia-envelo-3/meetek-front#23]
**Story**
W widoku sekcji wybieramy zakładkę 'uczestnicy', która przekierowuje nas na listę uczesników danej sekcji, Wyświetla mi się tytuł 'Uczestnicy', pole do wyszukiwania uczestników oraz lista uczestników.

**Dodatkowe informacje**
Na tym etapie wyszukiwarka nie działa.

Potrzebne jest tutaj skorzystanie z  selektora ngrx do pobierania uczestników. 

**Taski blokujące**
#22 

**Makiety**
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=319%3A18605&t=wIKCAUvRYvYDqQG3-0) UC29: Display section

**Kryteria akceptacji**
1. Widok zgodny z makietami, zachowana responsywność widoku. 
2. Logika zgodna z wyżej opisanym story.
3. Pojedynczy komponent listy wrzucony jest do storybooka. 

**Link do testowania**
(https://ft022-feat-wyswietlanie-listy-uczestnikow-sekcji--meetek-envelo.netlify.app/section/1/members)

**Comment by PawelJurga** [comment]
@EMEZYK dodaj link do tego taska i oznacz mnie jak przejdzie do QA

**Comment by PawelJurga** [comment]
- [ ] Widok zgodny z makietami, zachowana responsywność widoku.

**-  dla aplikacji desktop wprowadzenie wielu użytkowników powoduje rozjechanie się formularza** , dla mobile działa prawidłowo.
**- w przypadku dodania pustej sekcji na ekranie nie wyświetla się nic poza napisem "Uczestnicy"** - pytanie czy tak ma być ?

- [ ] Logika zgodna z wyżej opisanym story.

**-  brak wyszukiwarki - rozumiem że miała być ale nie działająca**

- [x] Pojedynczy komponent listy wrzucony jest do storybooka


**Do ustalenia zostaje liczba znaków jakie będzie można wpisać w przypadku pól "firstName", "lastName". Na załączonych screenech widać, że zbyt długie imiona i nazwiska powodują rozjechanie się formularza. Ponadto warto się zastanowić nad zablokowaniem znaków angielskich oraz cyfr.**



![Image](https://user-images.githubusercontent.com/121928858/214496762-217206c0-f4bc-4dca-9e9a-c03621accdeb.png)


![Image](https://user-images.githubusercontent.com/121928858/214496942-d88cbcf4-0edf-4769-9d2c-1da24c3748ad.png)

**Comment by EMEZYK** [comment]
Widok desktop został poprawiony - dodany scroll. 

Docelowo, będziemy w liście wyświetlać zawsze admina sekcji, jako domyślny użytkownik, lista nie będzie zatem nigdy pusta.

Wyszukiwarka zostanie dodana w innym tasku, na dany moment nie jest gotowa, zostanie dodana przy składaniu widoku.

Co do znakow specjalnych, dlugosci znakow etc - lista uczestników przyjdzie z backendu - przekażę im Twoje uwagi.

**Comment by PawelJurga** [comment]
**Retest**

Wszystko ok :), jest tylko jeszcze problem z rozjeżdżaniem się pola z inicjałami. Na screenach są wpisane najdłuższe nazwiska w Polsce. Trzeba dopasować widok tak , aby te inicjały się nie rozjechały. To przypadek z życia, który aplikacja powinna obsłużyć.


![Image](https://user-images.githubusercontent.com/121928858/214582044-7d1b743c-5060-4726-8fb9-32623ef62d2b.png)

**Comment by EMEZYK** [comment]
Ok, poprawione :)

**Comment by PawelJurga** [comment]
**Retest**
**Problem rozjeżdżania się pola z inicjałami został rozwiązany. WAŻNE ABY BACKEND UWZGLĘDNIŁ LIMIT ZNAKÓW DLA IMIENIA I NAZWISKA, BIORĄC POD UWAGĘ PRZYPADKI Z "ŻYCIA WZIĘTE"** (jak na załączonym screenie)


![Image](https://user-images.githubusercontent.com/121928858/214800244-eb3d53aa-6f21-4165-990c-cd2dcd6e6419.png)
**Rekomenduję zakończenie taska :)**
