### ISSUE TITLE
FT002 - config: instalacja JSON Server oraz JSON Server Auth

### ISSUE THREAD

**Issue by EMEZYK** [akademia-envelo-3/meetek-front#3]
**Dodatkowe informacje**
Zainstalowanie JSON Server oraz z JSON Server auth.
Konfiguracja package.json, tak żeby server odpalał się na npm run server.

**Przydatne strony**
[Diagram klas](https://app.diagrams.net/#G1eDc3Uwv7O-P8U4RuM_8SP80KC61FArkq)
[Endpointy](https://app.diagrams.net/#G1eDc3Uwv7O-P8U4RuM_8SP80KC61FArkq)
[Json Server](https://www.npmjs.com/package/json-server)
[JSON Server auth](https://www.npmjs.com/package/json-server-auth)

**Kryteria akceptacji**
1. Po uruchomieniu serwera (npm run server) dostaję w pełni funkcjonalny serwer z działającym API, który jako bazę danych używa pliku db.json.
2. Plik db.json dodany jest do git ignore.

**Comment by jBachanek-02** [comment]
@KamilWojkowskiEnvelo
