### ISSUE TITLE
FT024 - utworzenie serwisu do obsługi toastów

### ISSUE THREAD

**Issue by EMEZYK** [akademia-envelo-3/meetek-front#34]
**Dodatkowe informacje**
Należy zainstalować toastr angular.
W gotowych juz storach, w efektach, w miejscu gdzie mamy zakomentowany komunikat //Todo: add toast, nalezy dodac implementację wraz z odpowiednim komunikatem błędu.

1. W folderze shared dodany jest serwis (fasada), który zawiera w sobie metody do obsługi toastów (toastr angular).
2. W miejscach, gdzie toasty do tej pory były używane (user.effects, auth.effects oraz section.effects), dodane są toasty z odpowiednimi komunikatami błędu.
 

Link, do sprawdzenia:
(https://deploy-preview-58--meetek-envelo.netlify.app/auth)

**Kryteria akceptacji**
1. Po podaniu niewłaściwych danych logowania i kliknięciu w przycisk 'zaloguj', w prawym gornym rogu wyświetla się toast z komunikatem o błędzie.

**Comment by piodaw** [comment]
- [x] Po podaniu niewłaściwych danych logowania i kliknięciu w przycisk 'zaloguj', w prawym gornym rogu wyświetla się toast z komunikatem o błędzie.
