### ISSUE TITLE
FT031 - utworzenie modali

### ISSUE THREAD

**Issue by jBachanek-02** [akademia-envelo-3/meetek-front#40]
**Dodatkowe informacje** 
Utworzenie modali za pomocą angular material uwzględniając podane niżej informacje. Wygląd zgodny z design system.

Modal ma się odpalać w momencie kliknięcia w button plus odnoszący się do stworzenia nowej kategorii.
- Pierwszy modal z inputem:
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=307%3A16944&t=asExhTE2Aows1LjY-4)
1. Przycisk "X" w prawym górnym rogu modala.
2. Dodany tekst w zależności od tego w jakiej części aplikacji jesteśmy.
3. Input .
4. Przycisk (rodzaj przycisku tez zalezny od tego w jakiej części aplikacji jesteśmy.

Modal ma się odpalać w momencie kliknięcia w button "opuść" odnoszący się do opuszczenia sekcji.
- Drugi modal z dwoma przyciskami:
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=315%3A15335&t=asExhTE2Aows1LjY-4)
1. Przycisk "X" w prawym górnym rogu modala.
2. Dodany tekst w zależności od tego w jakiej części aplikacji jesteśmy.
3. Dwa przyciski zgodnie z makietami.

**Przydatne strony** 
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=250%3A8095&t=asExhTE2Aows1LjY-4)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0)

**Kryteria akceptacji** 
1. Wygląd zgodny z makietami z uwzględnieniem media queries
2. Dodać utworzone modale do komponentu "theme.component..ts"

**Comment by lkrzysztoff** [comment]
deploy https://ft031-utworzenie-modali--meetek-envelo.netlify.app/theme

**Comment by PawelJurga** [comment]
@lkrzysztoff 

   - [ ]   Wygląd zgodny z makietami z uwzględnieniem media queries

**- różne kolory ramki gdy input "dialog z inputem" jest sfokusowany, w zależności od przeglądarki oraz w przypadku przeglądarki Chrome znika napis"Example label**"




![Image](https://user-images.githubusercontent.com/121928858/215478007-c86fb380-7718-4c00-83f4-b6ebe9000103.png)

**- w mojej opinii należy usunąć podkreślenie buttonów. Wystarczy, że podświetlają się przy kliknięciu.**



![Image](https://user-images.githubusercontent.com/121928858/215479832-e9b4a1a2-a036-413f-9722-2142e11ecec9.png)


**- ustawić limit znaków dla inputu** 


   

- [x]  Dodać utworzone modale do komponentu "theme.component..ts"

**Comment by lkrzysztoff** [comment]
Poprawione https://ft031-utworzenie-modali--meetek-envelo.netlify.app/theme

**Comment by PawelJurga** [comment]
**RETEST**

- [x] Wygląd zgodny z makietami z uwzględnieniem media queries

- **zgłoszone błędy zostały naprawione (screen poniżej)**

![Image](https://user-images.githubusercontent.com/121928858/215683811-fcf919a3-6310-444b-9c03-94abe71994c5.png)
- _w mojej opinii należy usunąć podkreślenie buttonów. Wystarczy, że podświetlają się przy kliknięciu._  - **po konsultacji z zespołem Front ta funkcjonalność zostanie zmieniona w następnym sprincie**
- _ustawić limit znaków dla inputu_  - **limit ustalono na 50 znaków**

**Rekomenduję zakończenie taska :)**
