### ISSUE TITLE
FT032 - edycja sekcji

### ISSUE THREAD

**Issue by jBachanek-02** [akademia-envelo-3/meetek-front#41]
**Story**
Właściciel sekcji po kliknięciu w przycisk "Modyfikuj", przechodzi do formularza edycji sekcji. Zmieniając dane(nazwa / opis), wysyła zapytanie do backendu.  Klikając w przycisk zatwierdź, zapisywane są zmiany i dane sekcji zostają zmienione. Klikając przycisk 'odrzuć', zmiany są odrzucane i dane pozostają bez zmian.

**Dodatkowe informacje** 
1. pole "Nazwa", "Opis" oraz owner uzupełniają się automatycznie .
2. należy skorzystać z efektów store do edycji sekcji

**Przydatne strony** 
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=331%3A25376&t=ht9GjdriLijgnVFp-0)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0) 

**Kryteria akceptacji** 
1. Wygląd zgodny z makietami z uwzględnieniem media queries.
2. Klikając w przycisk modyfikuj, otwiera się formularz edycji sekcji wraz z autouzupełnionymi danymi.
3.Zmieniając dane i klikając w przycisk zatwierdź, zapisywane są zmiany.

**Comment by piodaw** [comment]
https://deploy-preview-79--meetek-envelo.netlify.app/section/1/edit

**Comment by PawelJurga** [comment]
- [ ] Wygląd zgodny z makietami z uwzględnieniem media queries.
- **problemy z wyświetlaniem użytkownika, oraz brak avatara podobnie jak w przypadku #10**

   

 

- [ ] Klikając w przycisk modyfikuj, otwiera się formularz edycji sekcji wraz z autouzupełnionymi danymi.
- **nie da się sprawdzić przycisku modyfikuj, ponieważ po kliknięciu w link z taska jestem od razu przekierowany na widok edycji sekcji**

 

- [x] Zmieniając dane i klikając w przycisk zatwierdź, zapisywane są zmiany.


**UWAGI**
Story - _...Klikając przycisk 'odrzuć', zmiany są odrzucane i dane pozostają bez zmian._ - **tego buttona nie ma na formularzu, na** **makietach też go nie widzę** 
**Myślę, że należy na wzór #10 dokonać blokady możliwości dodawania znaków w formularz zgodnie z komunikatami walidacyjnymi**




![Image](https://user-images.githubusercontent.com/121928858/216257440-6ec2205f-1823-403a-8c7e-7a0633084f48.png)

**Comment by piodaw** [comment]
przycisków przekierowujących też na tym etapie nie ma, bo nie jest gotowy widok wszystkich sekcji

**Comment by PawelJurga** [comment]
@piodaw 

**RETEST**
**Obecnie maksymalne wartości dla pól "nazwa" i "opis" to 30 oraz 250. Formularz nie pozwala na wpisanie większej ilości znaków, jednak nie wyświetla już komunikatów walidacyjnych. Pytanie czy tak ma być w wersji ostatecznej? . Moim zdaniem najlepszym rozwiązaniem jest pozostawienie tych komunikatów, aby użytkownik wiedział dlaczego nie może już wprowadzać znaków w formularzu.**

**Comment by PawelJurga** [comment]
**RETEST**
@piodaw **uwzględnił sugestie z komentarza powyżej**

- [x] Wygląd zgodny z makietami z uwzględnieniem media queries.
- **użytkownik wyświetla się poprawnie oraz dostosowano rozmiary tego pola do wartości w nim wyświetlanych**

- [x] Klikając w przycisk modyfikuj, otwiera się formularz edycji sekcji wraz z autouzupełnionymi danymi.
- **zostanie dodane w innym tasku**

**Rekomenduję zakończenie taska :)**
