### ISSUE TITLE
FT036 - feat: Stworzenie komponentu listy kategorii

### ISSUE THREAD

**Issue by piodaw** [akademia-envelo-3/meetek-front#44]
**Dodatkowe informacje**
Stworzenie komponentu kategorii w liście kategorii zgodnie z makietami.
Wykorzystanie mat-card (material design). 

**Inputy**
- nazwa
- ilość wydarzeń z daną kategorią
- czy aktywny

**Outputy**
- edycja
- aktywny / nieaktywny

**Lokalizacja**
features > categories > shared > category-list-item.component.ts

**Makiety**
[figma 1](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=307%3A17354&t=vUCybF0VMvaUlP2a-4)
[figma 2](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=314%3A21966&t=1C0iysgqqob8GNXC-4)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=JYt3CImqlQ4GD88X-0)

**Kryteria akceptacji**
- wygląd komponentu zgodny z makietami (z uwzględnieniem media queries)
- komponent wyświetla się zgodnie z przekazanymi inputami / outputami
- komponent umieszczony w podanej lokalizacji
- komponent dodany do theme

**Comment by damiankubecki** [comment]
podgląd: https://ft036-feat-stworzenie-komponentu-listy-kategorii--meetek-envelo.netlify.app/theme

**Comment by PawelJurga** [comment]
- [x]   wygląd komponentu zgodny z makietami (z uwzględnieniem media queries)

   

- [x]  komponent wyświetla się zgodnie z przekazanymi inputami / outputami


    

- [x] komponent umieszczony w podanej lokalizacji

   

- [x]  komponent dodany do theme

**Uwagi**
@damiankubecki 
Po przełączeniu toggla mija spora chwila zanim kursor zmieni się na pointer i na odwrót. Czy da się coś z tym zrobić ?

**Comment by PawelJurga** [comment]
![Image](https://user-images.githubusercontent.com/121928858/217239391-b3648b7b-8df5-48e5-bdcf-3f15cf9bc399.png)
**W związku z powyższym  
Rekomenduje zakończenie taska :)**
