### ISSUE TITLE
FT028 - nawigacja po evencie i sekcji

### ISSUE THREAD

**Issue by EMEZYK** [akademia-envelo-3/meetek-front#47]
**UWAGA** - na dany moment dodana jest nawigacja po sekcji, poniewaz nie mamy jeszcze widoku eventu;
Nie mamy jeszcze contentu dla wyswietlenia informacji o sekcji (ikonka 'i' oraz conentu, ktory ma sie wyswietlac po kliknieciu strzalki, dlatego na razie wyswietla sie tam puste strony.

**Figma**
Sekcja:
[Menu górne](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=319%3A19225&t=jR3wIeVNE4cQ56KM-4)
[Menu dolne](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=257%3A9236&t=jR3wIeVNE4cQ56KM-4)

~~Event - **na razie nie dotyczy:**
[Menu górne](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=298%3A22041&t=jR3wIeVNE4cQ56KM-4)
[Menu dolne](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=218%3A3361&t=jR3wIeVNE4cQ56KM-4)~~
**Nawigacja po evencie przeniesiona do oddzielnego taska:**
(https://github.com/akademia-envelo-3/meetek-front/issues/88)

**Dodatkowe informacje**
Działanie projektu można podejrzeć tutaj:
https://ft028-nawigacja-event-sekcja--meetek-envelo.netlify.app/section/1/members

obiekt json - ten sam, ktory byl uzywany przy wyswietlaniu uczestnikow sekcji 

**Kryteria akceptacji**
1. Do widoku sekcji dodana jest nawigacja: 
 a) w przypadku mobile: menu wyświeltane na dole; . Elementy nawigacji: strzałka powrotu, informacje o sekcji,  uczestnicy  (kazdy oznaczony odpowiednia ikonką).
 b) w przypadku widokow desktopowych i tablet: menu wyświetla się nad nagłówkiem - te same elementy nawigacji co w mobile.
~~2. Do widoku eventu dodana jest nawigacja po evencie:  **obecnie nie dotyczy**
 a) w przypadku mobile: menu wyświeltane na dole. Elementy nawigacji: strzałka powrotu, informacje, uczestnicy, konwersacja, załączniki
b) w przypadku widokow desktopowych: menu wyświetla się nad nazwą eventu.  Elementy nawigacji: strzałka powrotu, informacje, uczestnicy, konwersacja, załączniki~~
3. Po kliknięciu na element nawigacji, przenosi nad na odpoiednią podstronę.
4. Wybrana podstrona jest odpowiednio oznaczona kolorowym podkreślnikiem (patrz- Figma).
5. Elementy są responsywne (breakpointy zgodne z przyjętymi przez zespol) i odwzorowane zgodnie z widokami Figma.

**Comment by PawelJurga** [comment]
- [x] Do widoku sekcji dodana jest nawigacja:

    a) w przypadku mobile: menu wyświeltane na dole; . Elementy nawigacji: strzałka powrotu, informacje o sekcji, uczestnicy (kazdy oznaczony odpowiednia ikonką).
    b) w przypadku widokow desktopowych i tablet: menu wyświetla się nad nagłówkiem - te same elementy nawigacji co w mobile.
    

- [ ] ~~Do widoku eventu dodana jest nawigacja po evencie: obecnie nie dotyczy~~

    ~~a) w przypadku mobile: menu wyświeltane na dole. Elementy nawigacji: strzałka powrotu, informacje, uczestnicy, konwersacja, załącznik~~i
   ~~b) w przypadku widokow desktopowych: menu wyświetla się nad nazwą eventu. Elementy nawigacji: strzałka powrotu,~~ ~~informacje, uczestnicy, konwersacja, załączniki~~ **obecnie nie dotyczy**
    

- [ ] Po kliknięciu na element nawigacji, przenosi nad na odpowiednią podstronę.

- **w przypadku uczestników nigdzie nie przenosi (nawet do pustej strony)**

    

- [ ] Wybrana podstrona jest odpowiednio oznaczona kolorowym podkreślnikiem (patrz- Figma).

-  **w wersji desktop podkreślenie nie wędruje za kursorem po ikonach**
 

![Image](https://user-images.githubusercontent.com/121928858/215764687-d379624d-1384-4a46-86c4-877a915b8fea.png)

**- dla przeglądarki Firefox po przejściu w tryb mobilny i włączeniu symulacji dotknięć nie działają podświetlenia**



    

- [x] Elementy są responsywne (breakpointy zgodne z przyjętymi przez zespol) i odwzorowane zgodnie z widokami Figma.

**Comment by EMEZYK** [comment]
Jeśli chodzi o przenoszenie do uczestników sekcji, to domyślnie jesteś na routcie z uczestnikami, dlatego Cię nie przenosi.

Pozostałe kwestie - poprawione.

**Comment by PawelJurga** [comment]
**RETEST**
_w przypadku uczestników nigdzie nie przenosi (nawet do pustej strony)_ - **problem rozwiązany w komentarzu powyżej** 
_w wersji desktop podkreślenie nie wędruje za kursorem po ikonach_ - **błąd naprawiono**
_dla przeglądarki Firefox po przejściu w tryb mobilny i włączeniu symulacji dotknięć nie działają podświetlenia_ - **działanie zamierzone, po przejściu do wybranego widoku będzie się podświetlał odpowiedni element dla podstrony**

**Rekomenduję zakończenie taska :)**
