### ISSUE TITLE
FT037 - dodanie wyszukiwarki oraz toggla

### ISSUE THREAD

**Issue by jBachanek-02** [akademia-envelo-3/meetek-front#51]
Wyszukiwarka oraz toggle narazie bez logiki
dodane do theme.component.ts
razem ze stylami
dodać outputa

**Przydatne strony** 
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=331%3A25376&t=ht9GjdriLijgnVFp-0)
Aby zobaczyć widok wyszukiwarki należy na figmie zjechać trochę w dół i pokaże się komponent o tytule Search.

**Kryteria akceptacji** 
1. Wygląd zgodny z makietami.
2. Klikając w przycisk toggle zmienia kolor po kilknięciu.

**Comment by jBachanek-02** [comment]
https://ft037-dodanie-wyszukiwarki-oraz-toggla--meetek-envelo.netlify.app/theme link do widoku

**Comment by PawelJurga** [comment]
- [x] Wygląd zgodny z makietami.

- [x] Klikając w przycisk toggle zmienia kolor po kliknięciu.
**- do toggle nie mam zastrzeżeń**

**UWAGI**

**- w zależności od przeglądarki wyszukiwarka podświetla się w różny sposób, w dodatku w firefox ramka podświetlenia źle się skaluje (pojawia się biała ramka ). Analogiczna sytuacja dzieje się gdy odpalam /theme na telefonie**


![Image](https://user-images.githubusercontent.com/121928858/215417441-9ffed330-f5af-4eaf-9b40-1cbfa2eac44f.png)

**Comment by jBachanek-02** [comment]
@PawelJurga już zrobione

**Comment by PawelJurga** [comment]
**Retest**
**Błędy zostały naprawione. Wyszukiwarka prawidłowo się podświetla w przeglądarkach Firefox i Chrome (dla focus)**



![Image](https://user-images.githubusercontent.com/121928858/215681925-46871760-a43d-458a-bbfa-89b422b19415.png)


**Rekomenduję zakończenie taska :)**
