### ISSUE TITLE
FT006 - feat: - stworzenie formularza do logowania wraz z walidacją

### ISSUE THREAD

**Issue by EMEZYK** [akademia-envelo-3/meetek-front#6]
**Story**
Jako użytkownik  chcę zalogować się w systemie,  wypełniając formularz logowania. Chcę podać własny e-mail oraz hasło.

**Dodatkowe informacje**
 * Formularz powinien być walidowany: 
 * Ścieżka: /auth
 * Wszystkie widoki powinny być responsywne (breakpointy zgodne z design systemem).
 * Token zapisywany w cookies [Bilblioteka do tokenów](https://www.npmjs.com/package/ngx-cookie-service)

**Makiety**
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=0%3A1&t=ht9GjdriLijgnVFp-0)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0)

**Taski blokujące**
#3 

**Kryteria akceptacji**
1. Wygląd formularza odwzorowany jest zgodnie z makietami Figma.
2. Formularz jest responsywny, zgodnie z ustalonymi breakpointami.
3. Jako użytkownik chcę podać swój e-mail, używany w systemie oraz hasło.
4. Jako użytkownik chcę zobaczyć komunikaty walidacyjne dla pola e-mail:  błędny format lub puste pole. Min. ilość znaków:  10, max ilośc znaków: 100.
5. Jako użytkownik chcę zobaczyć komunikaty walidacyjne dla pola hasło: błędne hasłe lub puste pole.  
6. Chcę, aby wpisując hasło moje hasło, było ono ukrywane za gwiazdkami *** , a po kliknięciu na oczko, mogę je wyświetlić. 
7. Token zapisywany w cookies.
8. Po wpisaniu właściwych danych, chcę żeby po kliknięciu w przycisk 'Zaloguj się', przekierowało mnie na scieżkę home.

**Comment by PawelJurga** [comment]
@EMEZYK wrzuć w komentarz działający link do tego taska :)

**Comment by piodaw** [comment]
https://deploy-preview-30--meetek-envelo.netlify.app/auth

**Comment by PawelJurga** [comment]
- [ ]  Wygląd formularza odwzorowany jest zgodnie z makietami Figma.

-   nadmiarowe pogrubienie tekstu nagłówka "zaloguj się"
-   nieprawidłowe rozmiary pól "e-mail" oraz "hasło" oraz przycisku "zaloguj się" względem makiet
-   brak podświetlenia przycisku "zaloguj się" dla pustego formularza
-   powiększenie formularza powoduję ucięcie części logo

- [x]  Formularz jest responsywny, zgodnie z ustalonymi breakpointami.

    

- [x] Jako użytkownik chcę podać swój e-mail, używany w systemie oraz hasło.

    

- [ ] Jako użytkownik chcę zobaczyć komunikaty walidacyjne dla pola e-mail: błędny format lub puste pole. Min. ilość znaków: 10, max ilośc znaków: 100.

-  brak komunikatów walidacyjnych dla tego wymagania. **Oczekiwany komunikat "nieprawidłowy e-mail"**

- [ ] Jako użytkownik chcę zobaczyć komunikaty walidacyjne dla pola hasło: błędne hasłe lub puste pole.

- **aplikacja nie powinna dopuszczać możliwości logowania się hasłem złożonym z jednego znaku**

- [x]  Chcę, aby wpisując hasło moje hasło, było ono ukrywane za gwiazdkami *** , a po kliknięciu na oczko, mogę je wyświetlić.

    

- [x] Token zapisywany w cookies.

    

- [x] Po wpisaniu właściwych danych, chcę żeby po kliknięciu w przycisk 'Zaloguj się', przekierowało mnie na scieżkę home.




![Image](https://user-images.githubusercontent.com/121928858/212688647-3b9933ed-6d3a-410a-b9a6-20700607474f.png)

**Comment by PawelJurga** [comment]
**Retest błędów zgłoszonych**
 - [x] Wygląd formularza odwzorowany jest zgodnie z makietami Figma.

-  Po konsultacji z zespołem Front End zdecydowano o dostosowaniu makiety do widoku aplikacji na środowisku testowym.

- [x]  Jako użytkownik chcę zobaczyć komunikaty walidacyjne dla pola e-mail: błędny format lub puste pole. Min. ilość znaków: 10, max ilośc znaków: 100.
- [x]  Jako użytkownik chcę zobaczyć komunikaty walidacyjne dla pola hasło: błędne hasłe lub puste pole.

**Rekomenduję zakończenie taska :)**
