### ISSUE TITLE
FT005 - feat: formularz dodawania nowych kategorii

### ISSUE THREAD

**Issue by piodaw** [akademia-envelo-3/meetek-front#7]
**story**
* Admin:
1.  Po kliknięciu przycisku dodania nowej kategorii powinien wyświetlić się modal dodawania nowej kategorii
2. Po wpisaniu prawidłowej nazwy dodać kategorię do wszystkich kategorii i wyświetlić toast `Pomyślnie dodano nową kategorię`
3. Po wpisaniu nieprawidłowej nazwy wyświetlić błąd przy inpucie

**Dodatkowe informacje**
Stworzyć service który jest obsługiwany przez ngrx. W razie różnic z makietami zedytować makiety

**Dane do przechowania**
Kategorie (interfejs dostępny [tutaj](https://app.diagrams.net/#G1eDc3Uwv7O-P8U4RuM_8SP80KC61FArkq))

**taski blokujące**
#34 
#44 
#40 
#8

**makiety**
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=307%3A16961&t=vUCybF0VMvaUlP2a-4)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0) 

**kryteria akceptacji**
1. Po kliknięciu przycisku dodawania sekcji otwiera się modal
2. Walidacja inputu minlength: 3, maxlength: 20, brak możliwości wysłania formularza ze spacją
3. Wyświetlenie toastu po pozytwynym dodaniu kategorii
4. Nowa kategoria pojawia się we wszystkich kategoriach
5. widoki zgodne z makietami
6. Wszystkie widoki muszą być responsywne

**Comment by piodaw** [comment]
link: https://ft005-formularz-dodawania-kategorii--meetek-envelo.netlify.app/categories

json
```json
"categories": [
    {
      "name": "Test",
      "active": true,
      "id": 1
    }
  ],
```

**Comment by PawelJurga** [comment]
- [x] Po kliknięciu przycisku dodawania sekcji otwiera się modal

   

- [ ]  Walidacja inputu minlength: 3, maxlength: 20, brak możliwości wysłania formularza ze spacją

**- istnieje możliwość dodania kategorii uzupełniając formularz spacjami**


   

- [x]  Wyświetlenie toastu po pozytwynym dodaniu kategorii

   

- [x]  Nowa kategoria pojawia się we wszystkich kategoriach

   

- [x]  Widoki zgodne z makietami

    

- [x] Wszystkie widoki muszą być responsywne


![Image](https://user-images.githubusercontent.com/121928858/222146646-9bf8b3dc-d043-42ee-b493-e1eed894f9eb.png)

**Comment by PawelJurga** [comment]
**RETEST**
**Błąd naprawiono 
Rekomenduję zakończenie taska :)**
