### ISSUE TITLE
FT050 -Strona 404 Widok

### ISSUE THREAD

**Issue by jBachanek-02** [akademia-envelo-3/meetek-front#74]
**Dodatkowe infomacje**
1. Strona powinna zawierać informację o błędzie, np. "Strona nie została znaleziona" lub "Brak dostępu do zasobu".
2. Strona powinna zawierać odnośnik do głównej strony aplikacji, umożliwiający powrót do niej.
3. Strona powinna zawierać ikonę ilustrującą brak zasobu, np. ikona "404" lub "błąd"
4. Kolorystyka i styl strony powinny być zgodne z designem aplikacji.

**Makiety**
[figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=1248%3A22592&t=RsuehZw2AGkLa4T9-4)

**Kryteria akceptacji**
1. Strona zawiera odnośnik do głównej strony aplikacji.
2. Kolorystyka i styl strony są zgodne z makietami w Figmie.

**Comment by damiankubecki** [comment]
podgląd: https://ft050-feat-page404--meetek-envelo.netlify.app/dupa

**Comment by PawelJurga** [comment]
- [x] Strona zawiera odnośnik do głównej strony aplikacji.

   

- [x]  Kolorystyka i styl strony są zgodne z makietami w Figmie.
**Rekomenduję zakończenie taska :)**
