### ISSUE TITLE
FT009 - feat: Widok wszystkich kategorii

### ISSUE THREAD

**Issue by piodaw** [akademia-envelo-3/meetek-front#8]
**story**
* Admin:
Podczas wejścia na stronę z kategoriami, widocznej w menu bocznym, widzi:

1.  Wszystkie kategorie
2. Wyszukiwarkę
3. Przycisk do edycji oraz aktywacji /deaktywacji kategorii
4. Przycisk do dodawania nowych kategorii

* User:
Podczas wejścia na stronę z kategoriami, widocznej w menu bocznym, widzi:
1.  Wszystkie kategorie
2. Wyszukiwarkę
3. Przycisk do sugerowania kategorii - po kliknięciu wyświetla się modal  - na razie bez logiki sugerowania.

**dodatkowe informacje**
1.  Stworzenie service do pobierania danych z bazy, które są obsługiwane przez effecty w ngrx oraz poprzez reducer dodawane do lokalnego stora.

**taski blokujące**
#44 

**makiety**
[figma admin](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=304%3A16883&t=vUCybF0VMvaUlP2a-4)
[figma user](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=250%3A7933&t=BY7UF1vBhstMaRPX-4)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=JYt3CImqlQ4GD88X-0)

**kryteria akceptacji**
1.  Widok odwzorowany zgodnie z makietami
2.  Wszystkie widoki muszą być responsywne
3. Kategorie poprawnie się wyświetlają
4. Logika zgodna z wyżej opisanym story.

**Comment by piodaw** [comment]
https://ft009-widok-kategorii--meetek-envelo.netlify.app/categories

json do kategorii

```json
"categories": [
    {
      "categoryId": 1,
      "name": "Test",
      "active": true
    },
]
```

**Comment by PawelJurga** [comment]
- [x] Widok odwzorowany zgodnie z makietami

    

- [x] Wszystkie widoki muszą być responsywne

    

- [x] Kategorie poprawnie się wyświetlają

   

- [x]  Logika zgodna z wyżej opisanym story.


**Do taska zgłaszałem błędy @piodaw w wiadomościach priv, które były dynamicznie naprawiane. Dla wersji web wydaje się, że aktywne menu główne nie powinno przesuwać okna z kategoriami. Decyzja zespołu jest taka, aby pozostawić tą funkcjonalność w takiej formie.
Rekomenduję zakończenie taska :)**
