### ISSUE TITLE
FT010 - feat: dodanie edycji kategorii + effect

### ISSUE THREAD

**Issue by piodaw** [akademia-envelo-3/meetek-front#9]
**dodatkowe informacje**
Należy stworzyć service który jest obsługiwany przez effect w ngrx. W razie różnic z makietami zedytować makiety.
Należy skorzystać z interceptora do obsługi błędów po stronie serwera.

**story**
* Admin:
Po kliknięciu w przycisk edycji kategorii:

1.  Powinien pokazać się modal z możliwością zmiany nazwy
2. Wpisywana nazwa powinna byc sformatowana, np: 'Nowa sekcja'.
3.  Po kliknięciu edytuj zmienia się nazwa kategorii i wyświetla się toast z wiadomością `Pomyślnie zmieniono nazwę kategorii`
4. W przypadku błędu widzę komunikat o błędzie
5. W przypadku braku zmian, po kliknięciu w przycisk 'x', zamykam okno modala.

**taski blokujące**
#34 
#44 
#40 
#8 
#

**makiety**
[Figma](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=307%3A18328&t=vUCybF0VMvaUlP2a-4)
[Design system](https://www.figma.com/file/zEu3sivMxSapxiM9ehUs0s/MEETEK?node-id=325%3A17463&t=ht9GjdriLijgnVFp-0) 

**kryteria akceptacji**
1. Logika zgodna z wyżej opisanym story.
1. Po kliknięciu w przycisk edytuj dane się aktualizują.
2. Widoki zgodne z makietami.
3. Po pomyślnym zedytowaniu kategorii, wyświetla się toast z wiadomością o pomyslnym zedytowaniu.
4. Jeśli nastąpił błąd po stronie serwera, wyświelta się toast z komunikatem o błędzie.
5.  Wszystkie widoki są responsywne
6.  Walidacja inputu minlength: 3, maxlength: 20, brak możliwości wysłania formularza jesli jest sama spacja.

**Comment by piodaw** [comment]
https://ft010-edycja-kategorii--meetek-envelo.netlify.app/categories
żeby móc edytować kategorię trzeba być zalogowanym jako admin
json
```json
"categories": [
    {
      "name": "Test",
      "active": true,
      "id": 1
    }
  ],
```

**Comment by PawelJurga** [comment]
- [x] Logika zgodna z wyżej opisanym story.

   

- [x]  Po kliknięciu w przycisk edytuj dane się aktualizują.

    

- [x] Widoki zgodne z makietami.

    

- [x] Po pomyślnym zedytowaniu kategorii, wyświetla się toast z wiadomością o pomyslnym zedytowaniu.

    

- [x] Jeśli nastąpił błąd po stronie serwera, wyświelta się toast z komunikatem o błędzie.

    

- [x] Wszystkie widoki są responsywne

    

- [x] Walidacja inputu minlength: 3, maxlength: 20, brak możliwości wysłania formularza jesli jest sama spacja.

**Edycja #9 jak również tworzenia kategorii #7 nie zakładają dodawania nazw dwuczłonowych** 

**Rekomenduję zakończenie taska :)**
